import { Patrick_Hand } from "next/font/google";

const patrickHand = Patrick_Hand({
  weight: "400", // You can specify the weight, here it is 400 (regular)
  style: "normal",
  subsets: ["latin"],
  variable: "--font-patrick-hand", // Custom variable to use across the app
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={patrickHand.className}>{children}</body>
    </html>
  );
}
